remove deprecated assert
Mapotempo/optimizer-api pull request #125
Opened 2021-02-03 16:50 UTC by fonsecadeline

2021-02-04 08:12 UTC, braktar requested changes

2021-02-04 08:12 UTC, braktar commented on wrappers/vroom.rb
> +        :assert_no_planning_heuristic,
This assert is relative to the resolution method, it should belong to the Solver catgory

2021-02-04 09:35 UTC, braktar requested changes

2021-02-04 09:35 UTC, braktar commented on wrappers/vroom.rb
> +        :assert_no_planning_heuristic,
I would prefer to respect the alphabetic order :)

2021-02-04 09:47 UTC, braktar approved these changes

2021-02-11 09:22 UTC, senhalil approved these changes

2021-02-26 10:18 UTC, merged