Parse intermediate results
Mapotempo/optimizer-api pull request #179
Opened 2021-04-09 09:04 UTC by fonsecadeline

2021-04-21 07:48 UTC, braktar requested changes

2021-04-21 07:48 UTC, braktar commented on wrappers/ortools.rb
> +      OptimizerWrapper.parse_result(vrp, {
I would prefer to put the hash within a variable and then transmit it to the method : `OptimizerWrapper.parse_result(...)`

Having a multi-line argument is pretty hard to understand

2021-04-22 13:40 UTC, braktar approved these changes

2021-04-26 10:03 UTC, senhalil approved these changes

2021-05-27 07:33 UTC, merged