Scheduling move checks to find best index
Mapotempo/optimizer-api pull request #227
Opened 2021-06-04 09:10 UTC by fonsecadeline

- [ ] needs

2021-06-28 13:13 UTC, braktar approved these changes

2021-06-29 07:21 UTC, senhalil requested changes
Maybe I missed but I didn't see any unit or functionality non-regression tests against the capacity violation bug. Can we add a tests that breaks without this PR and gets fixed with it?

2021-06-29 07:21 UTC, senhalil commented on CHANGELOG.md
> +- Improve case where service has two visits in periodic heuristic : ensure second visit can be assigned to right day [#227](https://github.com/Mapotempo/optimizer-api/pull/227)
```suggestion
- Improve cases where a service has two visits in periodic heuristic: ensure that the second visit can be assigned to the right day [#227](https://github.com/Mapotempo/optimizer-api/pull/227)
```

2021-06-29 07:21 UTC, senhalil commented on CHANGELOG.md
> +- Capacity violation from periodic heuristic [#227](https://github.com/Mapotempo/optimizer-api/pull/227)
```suggestion
- Capacity violation in periodic heuristic algorithm (`first_solution_strategy='periodic'`) [#227](https://github.com/Mapotempo/optimizer-api/pull/227)
```

2021-06-29 07:21 UTC, senhalil commented on lib/heuristics/concerns/scheduling_end_phase.rb
> +    @uninserted.delete(uninserted_set.first) # faire en fct nb in seq
I can't really understand the comment.

2021-06-30 13:37 UTC, fonsecadeline commented
@senhalil in fact it is not possible to create a code that would fail without these edits, because checks were correctly done (repeatedly) everywhere (like in find_best_day_cost for instance). 

Now this capacity check is called at only once place and we are sure we are going to call it everytime we compute cost of inserting a service in a route. It was not the case before and I generated capacity violation while working on same_point_day improve. That is why I generated this PR.

2021-06-30 14:40 UTC, senhalil approved these changes

2021-07-06 09:39 UTC, merged