Fix avancement for max split
Mapotempo/optimizer-api pull request #415
Opened 2022-05-23 08:40 UTC by braktar

Simple fix before entire rework

2022-05-23 08:47 UTC, senhalil requested changes
This is not the proper fix -- `service_vrp[:split_level] = split_level` assignment is at an incorrect place. Because of this, the right branch will use the split_level of the last children of the left branch (when we are backtracking) -- which leads to higher split_levels on the right-hand side branch. service_vrp[:split_level] is modified during recursion. 

I already have the fix -- I remember telling you that I am on it already and you shouldn't bother.

2022-05-24 09:10 UTC, braktar commented on lib/interpreters/split_clustering.rb
> +        service_vrp[:split_level] = split_level
@senhalil This line allows to fix the constant increasing of the split_level by reverting the split_level to its value before the dive to a deeper level.

2022-05-24 09:10 UTC, braktar commented on lib/interpreters/split_clustering.rb
> +          if !service_vrp[:split_denominators].include?(2**service_vrp[:split_level])
This condition allows to initialize a new level never explored until now.

2022-05-24 09:10 UTC, braktar commented on lib/interpreters/split_clustering.rb
> +            service_vrp[:split_sides][split_level + 1] = 0
When arriving to a level already explored by another branch we reset the counter of this level. But it should be applied to every subsequent levels too

2022-05-24 09:10 UTC, braktar commented on lib/interpreters/split_clustering.rb
> +          if !service_vrp[:split_denominators].include?(2**service_vrp[:split_level])
```suggestion
          if service_vrp[:split_denominators].size < service_vrp[:split_level]
```

2022-05-24 09:10 UTC, braktar commented on lib/interpreters/split_clustering.rb
> +            service_vrp[:split_sides][split_level + 1] = 0
```suggestion
            (split_level + 1..-1).map{ |level| service_vrp[:split_sides][level] = 0 }
```

2022-05-24 09:13 UTC, senhalil commented on lib/interpreters/split_clustering.rb
> +        service_vrp[:split_level] = split_level
it is not at the correct place

2022-05-24 09:13 UTC, closed without merging