Don't accept matrix_id or matrix_index if no matrix
Mapotempo/optimizer-api pull request #62
Opened 2020-09-09 14:58 UTC by senhalil

2020-09-09 15:15 UTC, braktar requested changes
test?

2020-09-11 09:57 UTC, senhalil commented
@braktar  you can review again, the code quality changes are included as well.

2020-09-11 11:40 UTC, braktar approved these changes

2020-09-11 13:57 UTC, fab-girard commented on models/vrp.rb
> +          raise OptimizerWrapper::DiscordantProblemError, 'There is no matrix with id vehicle[:matrix_id]'
rescue this error for a 400 status code

2020-09-14 13:10 UTC, senhalil commented on models/vrp.rb
> +          raise OptimizerWrapper::DiscordantProblemError, 'There is no matrix with id vehicle[:matrix_id]'
Error codes are fixed.

2020-09-15 07:20 UTC, braktar approved these changes

2020-09-16 20:25 UTC, merged