add total_time and total_travel_distance when calling scheduling heur…
Mapotempo/optimizer-api pull request #63
Opened 2020-09-11 09:58 UTC by fonsecadeline

…istic

2020-09-14 13:22 UTC, senhalil requested changes

2020-09-14 13:22 UTC, senhalil commented on lib/heuristics/scheduling_heuristic.rb
> +            [0, 0]
Are these 0's relative to the start time of the vehicle or absolute (i.e., they will be shown on the solution file)? For ortools `start_time` is equal to a "valid" time (earliest_start for example) and end_time too even if the route is empty.

2020-09-14 13:45 UTC, senhalil approved these changes

2020-09-14 14:07 UTC, braktar approved these changes

2020-09-16 15:54 UTC, fab-girard commented on lib/heuristics/scheduling_heuristic.rb
> +        }.delete_if{ |_k, v| !v }
note you have a `compact` method with ActiveSupport

2020-09-16 20:26 UTC, merged