Ensure no duplicate ids in instance
Mapotempo/optimizer-api pull request #96
Opened 2020-12-21 15:24 UTC by fonsecadeline

To be abble to remove two instances from massive_tests.

2020-12-21 15:32 UTC, senhalil approved these changes
there are some typos otherwise :+1:

2020-12-21 15:32 UTC, senhalil commented on models/vrp.rb
> +      # TODO : Active Hash should be checking this
```suggestion
      # ensure IDs are unique
      # TODO: Active Hash should be checking this
```

2020-12-21 15:32 UTC, senhalil commented on models/vrp.rb
> +        raise OptimizerWrapper::DiscordantProblemError, "#{key} IDs should be uniq" unless hash[key].to_a.collect{ |v| v[:id] }.uniq!.nil?
```suggestion
        raise OptimizerWrapper::DiscordantProblemError, "#{key} IDs should be uniq" unless hash[key].to_a.collect{ |v| v[:id] }.uniq!.nil?
```
```suggestion
        raise OptimizerWrapper::DiscordantProblemError, "#{key} IDs should be unique" unless hash[key].to_a.collect{ |v| v[:id] }.uniq!.nil?
```

2020-12-23 08:49 UTC, fab-girard commented on test/instance_validity_test.rb
> +
can you add a functionnal test (in wrapper_test.rb) to check API returns a 400 http status code with duplicated IDs?

2021-01-19 11:11 UTC, senhalil approved these changes

2021-01-20 14:23 UTC, braktar approved these changes

2021-01-20 15:05 UTC, braktar requested changes

2021-01-20 15:05 UTC, braktar commented on models/vrp.rb
> +
Could you remove this extra line ?

2021-02-16 15:34 UTC, braktar requested changes

2021-02-16 15:34 UTC, braktar commented on test/wrapper_test.rb
> +      OptimizerWrapper.wrapper_vrp('demo', { services: { vrp: [:ortools] }}, TestHelper.create(vrp), nil)
```suggestion
      OptimizerWrapper.wrapper_vrp('demo', { services: { vrp: [:demo] }}, TestHelper.create(vrp), nil)
```

2021-02-19 08:19 UTC, braktar approved these changes

2021-02-19 16:16 UTC, senhalil approved these changes

2021-03-05 13:57 UTC, merged